version: '3.8'

services:
  db:
    container_name: app-ecityclic-db
    image: postgres:latest
    environment:
      POSTGRES_DB: PrimeraApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    container_name: app-ecityclic-backend
    build:
      context: ./AppEcityclicBack
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/PrimeraApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  frontend:
    container_name: app-ecityclic-frontend
    build:
      context: ./AppEcityclicFront
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  db_data: